return {

    MAX_TEAM_PLAYERS = 6,

    SPRINT_STAMINA_CONSUMPTION = 5,
    JUMP_STAMINA_CONSUMPTION = 4,
    DIVE_STAMINA_CONSUMPTION = 16,


    CAMERA_OFFSET = Vector3.new(0, 1.5, 0),

    MAX_STAMINA = 200,
    STAMINA_REGEN = 20,

    SHOT_CHARGE_MULTIPLIER = 2,
    SHOT_RECEDE_MULTIPLIER = 4,

    CURVE_FACTOR_CHARGE_MULTIPLIER = 1.5,
    CURVE_FACTOR_RECEDE_MULTIPLIER = 8.5,
    MAXIMUM_CURVE_FACTOR = 3.3,
    MINIMUM_CURVE_FACTOR = 0.3,

    SHOT_DISTANCE_MULTIPLIER = 1,
    
    DIVE_COOLDOWN = 1,
    DIVE_VELOCITY_DURATION = 0.5,
    DIVE_DURATION = 0.4,

    TACKLE_FRICTION = 0.19,
    TACKLE_VELOCITY_DURATION = 0.4,
    TACKLE_DURATION = 0.6,
    SKILL_DURATION = 0.7,

    TACKLE_RAGDOLL_TIME = 2,

}
